site_name: MZBench Docs
site_description: Expressive, Scalable Load Testing Tool

repo_url: http://github.com/machinezone/mzbench/

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - admonition
    - abbr
    - def_list

docs_dir: doc

pages:
- Overview: 'index.md'
- Scenarios:
    - How to Write a Scenario: 'scenarios/tutorial.md'
    - Scenario DSL Specification: 'scenarios/spec.md'
- Dashboard: 'dashboard.md'
- CLI: 'cli.md'
- API: 'api.md'
- Deployment: 'deployment.md'
- Cloud Plugins: 'cloud_plugins.md'
- Workers: 'workers.md'
