site_name: MZBench Docs
site_description: Expressive, Infinitely Scalable Load Testing Tool

repo_url: http://github.com/machinezone/mzbench/

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - admonition
    - abbr
    - def_list

docs_dir: doc

pages:
- Home: index.md
- Scenarios: scenarios.md
- Server API: server_api.md
- Workers: workers.md
- Cloud Plugins: cloud_plugin.md
- Deployment: deployment_guide.md