site_name: MZBench Docs
site_description: MZBench is an expressive and robust load testing tool

repo_url: http://github.com/moigagoo/mzbench/

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - admonition

docs_dir: doc

pages:
- Home: index.md
- Deployment: deployment_guide.md
- Scenarios: scenario_dsl.md
- Server API: server_api.md
- Workers: worker_howto.md
- Cloud Plugins: cloud_plugin.md